### ISSUE TITLE
ver.1.1.x ランキングシステム クライアントサイドのソートについて

### ISSUE THREAD

**Issue by TaikiFnit** [irc-archery/Archery-Server#1]
現在の仕様では、同試合に所属する得点表をユーザーごとの最新の得点が記載されている得点表データだけを送信しているため、それ以外の得点表がそのユーザーの最高得点になった場合に対応できないという仕様上の問題に気づきました。

この問題を対処するためには、
1. ソートされたランキングデータ( とは別に or をなくして ), ソート前のすべての得点表データをサーバーからクライアントに送信し、クライアントサイドでユーザーの最高得点を記載した得点表を抽出、のちそのデータでランキングソートする
2. broadcastを使わず、全データを取得(appサイドが処理落ちするやつ)
3. その他の方法
があると考えられます。

これについて、次のミーティングで話し合いたいと思います。
また、今意見がある場合は、このissueのコメント欄に書いてもらえるとありがたいです。

**Comment by nedoopg** [comment]
Ver1.1.xはそっちだけな

それはいいんだが、同時に複数の自分の得点表を更新することってあるか？

あったとしても、ランキング画面をリロードしたら、ちゃんと表示されるんでしょ？

気にしなくていいんじゃないんすか？

**Comment by TaikiFnit** [comment]
例えば、試合のはじめに顧問の先生がランキングページを見て、そのまま2得点表目に突入した場合、さらにその2得点表目が1得点表目より得点が大きかったとしても、現在の仕様では1得点表目のデータしか送っておらず、2得点表目のデータがわからないので比較しようがない状況ではないかってことです。

**Comment by nedoopg** [comment]
分かってる

それでも問題ないと思いますけどねぇ…

あえて仕様を変えるとしたら、ブロードキャストをそっちが送る前にいちいち比較、いいのがあったら送るってことか？

でも、こっちscidで判断してるから新しいイベントがほしいな

Scid何番より何番がいいの何番を送ってもらえれば簡単にこっち対応できるわ

**Comment by TaikiFnit** [comment]
broadcastは得点表一覧データで使っているものを流用しているだけだから、大きくは変えられない。
だけど、p_idを付属させることくらいはできると思う。もしくは、nedoがいうように新しいイベントを実装するか。

broadcastで送られてくるデータは
On Event Name : broadcastInsertScore
On Data Format :

```
{
    'sc_id': int,               // 得点表のID
    'perEnd': int,              // 何セット目の得点か
    'score_1': string,  // 1射目の得点
    'score_2': string,  // 2射目の得点
    'score_3': string,  // 3射目の得点
    'score_4': string,  // 4射目の得点
    'score_5': string,  // 5射目の得点
    'score_6': string,  // 6射目の得点
    'subTotal': int     // そのセットの小計
    'ten': int,         // 全セットの10数
    'x': int,           // 全セットのx数
    'total': int        // 全セットの合計
}
```

こんな感じだから、このデータ内にp_idを含ませるようにしてクライアントサイドもランキングだけp_idで判別するようにすればもしかしたら対処できるかもしれない。

**Comment by nedoopg** [comment]
とうとうネドって言われたo(^o^)o

俺のは新しいブロードキャストつくろうぜって話。

まあpidでも対処できるかなぁ

ただそうなるとランキングはpid順に並べることになるけどいいの？

**Comment by TaikiFnit** [comment]
今実装し終わったサーバーサイドの仕様では、p_idでソートしてある。
ランクでソートして送ってもいいけど、現在のランキングの外部設計では順位の数値だけを動的に変更するようになっていたはずだからランク順(1位が一番上)で送ってもあまり意味がないようなきがする。

ちなみに、このissueはopenにしてあるはずだから、つまりインターネット上publicな会話だから一応実名はここでは使わないことにした。

**Comment by TaikiFnit** [comment]
toyaにも確認取ったけど broadcastInsertScoreとbroadcastUpdateScoreにp_idを付加させるという仕様に変更しても大丈夫ですか?
あと、メンバー全員に連絡しておきます。

**Comment by TaikiFnit** [comment]
これに伴って、web, android, iosサイドもp_idをkeyとしてランキングを更新してもらうことになります。

**Comment by nedoopg** [comment]
りょーかい

一人偽名？になってない人いたがwww

仕様についてはこっちがわも直ぐに対応できると思う。

結論からいうと、ブロードキャストは       scid➡pidでいいんすかね？ふにっとさん

**Comment by nedoopg** [comment]
まとめて送ってくれ(￣▽￣;)

**Comment by TaikiFnit** [comment]
おｋです。
ただ、得点表一覧ではsc_idで参照していると思われるので、これまでのイベント(broadcastInsertScore, broadcastUpdateScore)のsc_idをp_idでreplaceするのではなく、p_idをaddする感じで行きたいと思います。
(つまりランキングページでは、sc_idは使わないことになります。 )

**Comment by nedoopg** [comment]
りょーかい

少し確認だが、同じ人が二つ目の得点表を作ったとする。

その場合、同じpidが増えるってことでいいのかな？

こっちはそれを省いて置いた方がいいのかな？

**Comment by TaikiFnit** [comment]
ふたつ目の得点表がランキングを見ている際に作られて、かつその得点表の得点(broadcastで取得が現在表示されている得点表の得点(extract時に取得)より大きくなったら, 表示されている得点をbroadcastで送られてきた得点をreplaceして、そのreplaceした結果を踏まえてまたランキングを再構築する感じです。

**Comment by TaikiFnit** [comment]
つまり、同じp_idの得点表がランキングリスト上に2つ以上現れることはないってことです。

**Comment by nedoopg** [comment]
すまん、こっちが色々とごちゃまぜになってたわ

全部了解です！

あと、仕様書完全なの出来たら教えてね♪

**Comment by TaikiFnit** [comment]
通信仕様書を更新しました。(p_idを追加)

"20160123 Args Server  WebSocket Event List.txt"をDropboxの共有にupload.

そのうちgithubにも上げます

**Comment by nedoopg** [comment]
りょーかい

お疲れさんです
2016/01/23 11:28 "TaikiFnit" notifications@github.com:

**Comment by TaikiFnit** [comment]
## broadcastのp_idについて

仕様書には書いてありませんでしたが、すでにbroadcastInsertScore, broadcastUpdateScoreでp_idを送信していたようです。
ゆえに、今回のissueでのサーバーサイドのプログラムの変更点は特にありません。
クライアントサイドは、ランキング画面では、sc_idは使わず、p_idで得点表参照し、得点・順位を更新してもらえると各クライアント間で結果に差が出ることはなくなると思います。
よろしくお願いします。

**Comment by nedoopg** [comment]
了解
